---

- name: Deploy 3-tier apps on top of the OSP infrastructure
  hosts: jumpbox
  gather_facts: false
  vars:
    cloud_name: ospcloud
  roles:
    - {name: osp-facts, tags: osp-facts}

- name: Deploy PostgreSQL server
  become: true
  hosts: appdbs
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [db-tier, dbs, PostgreSQL]}

- name: Deploy application servers
  become: true
  hosts: apps
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [app-tier, apps, Tomcat]}

- name: Deploy load balancer servers
  become: true
  hosts: frontends
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lb-tier, lbs, HAProxy]}

- name: Smoke test the 3 Tier application
  hosts: jumpbox
  gather_facts: false
  tasks:
    - name: Check frontend(s) is responding on port 80
      uri:
        url: "http://{{ item }}"
        return_content: yes
      register: webpage
      with_items:
        - "{{ groups['frontends'] }}"

    - name: Fail if the page content does not have <Ansible has done its job>
      fail:
      when: '"Ansible has done its job - Welcome to Tomcat" not in item.content'
      with_items: "{{ webpage.results }}"

...
